#!/bin/bash

rm -r gh-pages/*
mkdir -p gh-pages/javascripts

cp -r lib gh-pages/javascripts/
cp build/*.js gh-pages/javascripts

node build/cli.js demo.haml > gh-pages/index.html
node_modules/.bin/styl -w < demo.styl > gh-pages/style.css
